### ISSUE TITLE
deploy/service.yaml doesn't have valid image for argo-service deployment specified for release-0.1.0 branch

### ISSUE THREAD

**Issue by abhianand09** [keptn-contrib/argo-service#29]
Hi,
I was trying out keptn with argoCD example by following this doc https://keptn.sh/docs/0.6.0/usecases/deployments-with-argo.

Image mentioned for the argo-service deployment in https://github.com/keptn-contrib/argo-service/blob/release-0.1.0 is keptn/argo-service:0.1.0 which is wrong as that repo argo-service doesn't exist with keptn organization in dockerhub.It should be keptncontrib/argo-service but release tag release-0.1.0 is not present for keptncontrib/argo-service as well.

For all other releases it is keptncontrib/argo-service. 

Regards,
Abhishek Anand

**Comment by donovanmuller** [comment]
Hi @abhianand09, the tutorial you're using is very old and has not been updated for the latest releases (`0.8.x`) as far as I can see.

The closest comparative tutorial is [Keptn Multi Stage Delivery with Argo Rollouts and Dynatrace on k3s](https://tutorials.keptn.sh/tutorials/keptn-argo-rollouts-dynatrace-08-on-k3s/index.html?index=..%2F..index).

**Comment by abhianand09** [comment]
Yes @donovanmuller  But i wanted to try with Prometheus instead of Dynatrace.
Is there any specific link that you can provide for the same?

**Comment by donovanmuller** [comment]
There are multiple Prometheus [tutorials](https://tutorials.keptn.sh/) that you could probably swap out Dynatrace for Prometheus with. Otherwise, maybe join the Keptn [Slack](https://keptn.sh/community/#slack) workspace and ask for guidance there (good community).

**Comment by abhianand09** [comment]
Thanks @donovanmuller :thumbsup:

**Comment by christian-kreuzberger-dtx** [comment]
Closing this, as it should not be relevant anymore.
