### ISSUE TITLE
Do not use clusterAdmin role for argo-service

### ISSUE THREAD

**Issue by pchila** [keptn-contrib/argo-service#44]
Argo-service serviceaccount is currently bound to the `cluster-admin` role which has way too many permission.
https://github.com/keptn-contrib/argo-service/blob/41cf1c73ba019e253685b3372c0eb603b3455bc4/deploy/service.yaml#L24-L39

We need to use a (Cluster)Role having only the minimum set of permission necessary, we can expand the `keptn-argo-service-rollouts` ClusterRole as needed:
https://github.com/keptn-contrib/argo-service/blob/41cf1c73ba019e253685b3372c0eb603b3455bc4/deploy/service.yaml#L10-L22

# Definition of Done

- [ ] Argo-service serviceAccount is no longer bound to `cluster-admin` role

**Comment by TannerGabriel** [comment]
@christian-kreuzberger-dtx @pchila Does anyone have a list of the concrete permission this service needs, or do we need to find the permission by trial and error?
